# In .github/workflows/python-ci.yml
name: Python CI

#Trigger the workflow when a push or pull request is made to the main branch
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

#Define the jobs to be run
jobs:
    build:
        #Run on ubuntu-latest
        runs-on: ubuntu-latest
    
    steps:
        #Checkout the code
        - name: Checkout code
          uses: actions/checkout@v4

        #Set up Python
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        
        #Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        #Run tests
        - name: Run tests
          run: |
            pytest
        