# In .github/workflows/python-ci.yml
name: Python CI

#Trigger the workflow when a push or pull request is made to the main branch
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

#Define the jobs to be run
jobs:
    test-application:
        #Run on ubuntu-latest
        runs-on: ubuntu-latest
    
        steps:
            #Checkout the code  
            - name: Checkout code
              uses: actions/checkout@v4

            #Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.12
            
            #Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            #Run tests
            - name: Run tests
              run: |
                pytest

    build-and-push-docker-image:  
        needs: test-application
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4

          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.PAT }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
                # Example tag will be ghcr.io/phrochaf/freedom_project:a1b2c3d4...        